- description: Operator image
  name: IMAGE
  value: quay.io/redhat-services-prod/insights-management-tenant/insights-floorist/floorist-operator
- description: Operator image tag
  name: IMAGE_TAG
  value: ''
  required: true
